# Generated by Django 5.1.2 on 2024-10-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Task Title')),
                ('description', models.TextField(help_text='Provide a detailed description of the task.', verbose_name='Task Description')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('completed', 'completed')], default='pending', max_length=20, verbose_name='Task Status')),
                ('due_date', models.DateTimeField(help_text='Specify the due date and time for the task.', verbose_name='Due Date')),
            ],
        ),
    ]
